import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Button from '../components/button.js';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>CSICon Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable} container-fluid` }
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/images/CSICon2024_Banner_v1.png"
            alt="alt"
            width={1000}
            height={200}
            priority
          />
          <Button text="Click Me" />
        
        </main>
      </div>
    </>
  );
}
